# Generated by Django 3.0.5 on 2020-08-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='role',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
